name: Setup MinGW environment
description: Download and setup MinGW environment for Windows
inputs:
  mingw-version:
    description: The release tag from mstorsjo/llvm-mingw to use
    required: false
    default: "20240619"

runs:
  using: "composite"
  steps:
    - if: runner.os != 'Windows'
      name: Error when used on non-Windows runners
      run: |
        echo "::error::This action does not support $RUNNER_OS"
        exit 1
      shell: bash

    - name: Download from llvm-mingw
      id: download
      uses: robinraju/release-downloader@v1.10
      with:
        repository: mstorsjo/llvm-mingw
        tag: ${{ inputs.mingw-version }}
        fileName: llvm-mingw-${{ inputs.mingw-version }}-ucrt-x86_64.zip

    - name: Extract MinGW and add to PATH
      run: |
        7z x "$env:MINGW_ARCHIVE"
        rm $env:MINGW_ARCHIVE
        Join-Path $env:RUNNER_TEMP $env:MINGW_FOLDER "bin" | Out-File -Append $env:GITHUB_PATH
      shell: pwsh
      env:
        MINGW_ARCHIVE: ${{ fromJson(steps.download.outputs.downloaded_files)[0] }}
        MINGW_FOLDER: llvm-mingw-${{ inputs.mingw-version }}-ucrt-x86_64
      working-directory: ${{ runner.temp }}

    - name: Print GCC version
      run: gcc -v
      shell: pwsh
