name: Dispatch slash commands

on:
  issue_comment:
    types:
      - created

jobs:
  dispatch:
    name: Dispatch command
    runs-on: ubuntu-latest
    steps:
      - id: token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CHORE_APP_ID }}
          private_key: ${{ secrets.CHORE_APP_KEY }}

      - uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ steps.token.outputs.token }}
          reaction-token: ${{ steps.token.outputs.token }}
          commands: |
            merge
          issue-type: pull-request
          permission: write
